### ISSUE TITLE
MORNING SESSION: Peer-to-Peer code review

### ISSUE THREAD

**Issue by Dmambo** [Trast00/reimangined-conference#2]
# Changes Required ♻️ 

Your code looks good, however, there are some changes I think might make your code look much better.
Below is the list of changes I think you should implement in your code.

- [x] Please document your code too. it makes it easier to read.
- [x]  We suggest you make the email interactive
- [x]  kindly make your commit messages start with imperative verbs.  EXAMPLE "_Modified the CSS file for linter errors_"
- [x]  Please fill in the alt attributes in your images.

**Comment by Lookingfor00** [comment]
# Fixed
Hi, thank you for these helpful suggestions. 👍  

I made the required changes ([Pull Request: Fix Issues #1 and #2](https://github.com/Trast00/reimangined-conference/pull/4)):

- [x] Documented the code with comments in all the files
- [x] Made the email interactive
- [x] I will make sure that the next commit messages start with Upper-cases imperative verbs
- [x] Fill the alt attribute for `alt` the `img`

Don't hesitate to open an issue if you have any other issues, I will be grateful.
