### ISSUE TITLE
Changes Required

### ISSUE THREAD

**Issue by IsmailChangezi** [Trast00/reimangined-conference#3]
## Suggestions 
You have done a pretty good job but still, there are things you should work on.
- It would be better if you aligned your texts as their respective parent element.
- On the mobile version I could see some text overflow I suggest you fix those as it causes the page to be hard to read.

**Comment by Lookingfor00** [comment]
Hi, thank you for these helpful suggestions. 👍  

I made the required changes ([Pull Request: Fix Issues #1 and #2](https://github.com/Trast00/reimangined-conference/pull/4)):
 Before correction:
- [x] aligned the text as their respective parent element (aligned the first `summit-description` in the `list-summits`)
![Before correction](https://user-images.githubusercontent.com/74411135/205321123-426a1bcd-8661-4656-a016-0cec22137abf.png) 
After correction:
![After the correction](https://user-images.githubusercontent.com/74411135/205321490-b1b4494d-c1e0-425d-b633-9fb74e7e4177.png)

- [x] On the mobile version I could see some text overflow I suggest you fix those as it causes the page to be hard to read. (Add background to the header in the mobile version)
 Before correction:
![Before correction](https://user-images.githubusercontent.com/74411135/205322704-99908fba-da43-45cb-aeec-1af5db3ef983.png)

After correction:
![After correction](https://user-images.githubusercontent.com/74411135/205322497-35c779fd-0a6b-44c1-a049-4d68af94981b.png)

Don't hesitate to open an issue if you have any other issues, I will be grateful.
